# render.yaml

services:
  - type: web
    name: waffle-shop
    runtime: python
    plan: starter
    region: oregon
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app --host=0.0.0.0 --port=$PORT

    envVars:
      - key: FLASK_ENV
        value: production

      # ———————————————————————————————
      # 1) Internal connection (private VPC)
      # ———————————————————————————————
      - key: DATABASE_URL
        fromDatabase:
          name: budka_gofrowa
          property: connectionString

databases:
  - name: budka_gofrowa
    databaseName: budka_gofrowa
    plan: starter
    region: oregon
